## Processamento matemático e científico

+ [Pacote Numpy](#section_numpy)
+ [Pacote Scipy](#section_scipy)
+ [Pacote pandas](#section_pandas)

### Aprofundamento

Abaixo alguns notebooks onde são detalhados alguns pontos de cada biblioteca
+ [Pacote Numpy](./numpy.ipnb)
+ [Pacote Scipy](./scipy.ipynb)
+ [Pacote pandas](./pandas.ipynb)


<a id='section_numpy'>Numpy</a>

Um objeto numpy é uma tabela de objetos, normalmente números do mesmo tipo


<a href='https://numpy.org/devdocs/user/quickstart.html'>https://numpy.org/devdocs/user/quickstart.html</a>

### Uma motivação


In [1]:
a = list(range(4))
b = list(range(0,8,2))
print(a, b)


[0, 1, 2, 3] [0, 2, 4, 6]


Como ficaria uma soma?

In [2]:
a + b

[0, 1, 2, 3, 0, 2, 4, 6]

Exercício
--------
Utilize o zip para realizar a soma dos elementos da lista a com *a* lista *b*

In [3]:
import numpy as np
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [4]:
type(a)

numpy.ndarray

In [5]:
a.shape

(3, 5)

In [6]:

a.ndim


2

In [7]:
a.dtype.name


'int32'

In [8]:
a.itemsize

4

In [9]:
a.size

15

In [10]:
b = np.array([6, 7, 8])
b

array([6, 7, 8])

<a id='#section_scipy'>Scipy</a>

<a href='https://docs.scipy.org/doc/scipy/reference/tutorial/basic.html'>https://docs.scipy.org/doc/scipy/reference/tutorial/basic.html</a>

In [11]:
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt

In [12]:
a = np.concatenate(([3], [0]*5, np.arange(-1, 1.002, 2/9.0)))
a

array([ 3.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        , -1.        , -0.77777778, -0.55555556, -0.33333333,
       -0.11111111,  0.11111111,  0.33333333,  0.55555556,  0.77777778,
        1.        ])

In [13]:
a = np.r_[3,[0]*5,-1:1:10j]
a

array([ 3.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        , -1.        , -0.77777778, -0.55555556, -0.33333333,
       -0.11111111,  0.11111111,  0.33333333,  0.55555556,  0.77777778,
        1.        ])

**var[lower:upper:step]**

In [14]:
a[0:10:2]

array([ 3.        ,  0.        ,  0.        , -1.        , -0.55555556])

In [15]:
b = np.arange(0,12).reshape(6,2)
b.astype(float)

array([[ 0.,  1.],
       [ 2.,  3.],
       [ 4.,  5.],
       [ 6.,  7.],
       [ 8.,  9.],
       [10., 11.]])

Masked Array
------------
<a href='https://docs.scipy.org/doc/numpy/reference/maskedarray.generic.html'>https://docs.scipy.org/doc/numpy/reference/maskedarray.generic.html</a>

In [16]:
import numpy as np
import numpy.ma as ma
x = np.array([1, 2, 3, -1, 5])

# Operações com matrizes

In [17]:
%whos

Variable   Type       Data/Info
-------------------------------
a          ndarray    16: 16 elems, type `float64`, 128 bytes
b          ndarray    6x2: 12 elems, type `int32`, 48 bytes
ma         module     <module 'numpy.ma' from '<...>\numpy\\ma\\__init__.py'>
mpl        module     <module 'matplotlib' from<...>matplotlib\\__init__.py'>
np         module     <module 'numpy' from 'C:\<...>ges\\numpy\\__init__.py'>
plt        module     <module 'matplotlib.pyplo<...>\\matplotlib\\pyplot.py'>
x          ndarray    5: 5 elems, type `int32`, 20 bytes


In [36]:
a = np.random.random((2, 2))
b = np.random.random((2, 2))
a = np.eye((2))

a[1, 0] = 1
print(a)
print(b)

[[1. 0.]
 [1. 1.]]
[[0.51700788 0.69965182]
 [0.4194685  0.17173273]]


In [37]:
a * b

array([[0.51700788, 0.        ],
       [0.4194685 , 0.17173273]])

In [39]:
a.dot(b)

array([[0.51700788, 0.69965182],
       [0.93647638, 0.87138455]])